services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  CreditMergeBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  CreditMergeBundle\Command\:
    resource: '../../Command/'
  CreditMergeBundle\Service\:
    resource: '../../Service/'
    public: true
  CreditMergeBundle\Repository\:
    resource: '../../Repository/'
